Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -15,7 +15,13 @@ phases:
   build:
     commands:
       - echo Building the JAR file...
-      - mvn clean install || { echo "Maven build failed"; exit 1; }
+      - |
+        for i in {1..3}; do
+          mvn clean install -Dmaven.wagon.http.retryHandler.count=3 && break || {
+            echo "⚠️ Maven build failed (attempt $i)... retrying in 10 seconds"
+            sleep 10
+          }
+        done
       - echo Building Docker image...
       - docker build -t spring-demo-ecr:$IMAGE_TAG .
       - docker tag spring-demo-ecr:$IMAGE_TAG $REPO_URI:$IMAGE_TAG
